# Generated by Django 3.2.9 on 2022-02-26 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='messgaelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('file', models.FileField(upload_to='file/8b22c9f2-8f2f-4e65-af04-386955931fb5/', verbose_name='文件')),
                ('text', models.TextField(blank=True, max_length=4096, null=True, verbose_name='备注')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('allpeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='文件所有者')),
            ],
            options={
                'verbose_name': '文件列表',
                'verbose_name_plural': '文件列表',
            },
        ),
    ]
